"""
Engagement module — handles replies to mentions.

Engagement is limited to replying to accounts that mention @Qwinahh.
All replies are generated by Claude to be genuinely responsive to the
incoming tweet, not a canned response.

Requires X API Basic tier for the mentions endpoint.
"""
from __future__ import annotations

import logging
import os
from typing import Optional

import anthropic

from bot.config import CLAUDE_MAX_TOKENS, CLAUDE_MODEL, ENV, require_env
from bot.state import State
from bot.x.client import get_mentions, post_tweet

log = logging.getLogger(__name__)

# Replies are limited to this many per engage run to avoid rate-limit issues.
MAX_REPLIES_PER_RUN = 5

_REPLY_SYSTEM = """\
You write short, genuine replies for a crypto commentary account on X.

Rules:
- Be direct and helpful. No filler.
- Max 240 characters.
- If the mention is hostile or nonsensical, reply with a calm one-liner or skip entirely (respond with SKIP).
- Do not make price predictions.
- Do not promise financial returns.
- No hashtags.
"""


def _generate_reply(mention_text: str) -> Optional[str]:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        log.warning("ANTHROPIC_API_KEY not set — skipping reply generation.")
        return None

    client = anthropic.Anthropic(api_key=api_key)
    prompt = f"Mention received:\n\n{mention_text}\n\nWrite a reply, or respond with SKIP if a reply isn't appropriate."

    try:
        message = client.messages.create(
            model=CLAUDE_MODEL,
            max_tokens=CLAUDE_MAX_TOKENS,
            system=_REPLY_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        reply = message.content[0].text.strip()
        if reply.upper().startswith("SKIP"):
            log.debug("Skipping reply (model decided not to respond).")
            return None
        if len(reply) > 280:
            reply = reply[:276].rsplit(".", 1)[0] + "."
        return reply
    except anthropic.APIError as exc:
        log.error("Anthropic API error generating reply: %s", exc)
        return None


def run(state: State) -> int:
    """
    Check for new mentions and reply to them.

    Returns the number of replies sent.
    """
    since_id = state._data.get("last_mention_id")
    mentions  = get_mentions(since_id=since_id)

    if not mentions:
        log.info("No new mentions.")
        return 0

    # Update the cursor so we don't re-process old mentions.
    newest_id = max(m["id"] for m in mentions)
    state._data["last_mention_id"] = newest_id

    already_replied = state.last_replied_to()
    replies_sent    = 0

    for mention in mentions:
        if replies_sent >= MAX_REPLIES_PER_RUN:
            break

        tweet_id = mention["id"]
        if tweet_id in already_replied:
            continue

        reply_text = _generate_reply(mention["text"])
        if not reply_text:
            continue

        sent_id = post_tweet(reply_text, reply_to_id=tweet_id)
        if sent_id:
            state.mark_replied(tweet_id)
            replies_sent += 1
            log.info("Replied to %s: %s", tweet_id, reply_text[:60])

    return replies_sent
