"""
Engagement module — handles replies to mentions.

Engagement is limited to replying to accounts that mention @Qwinahh.
All replies are generated by Claude to be genuinely responsive to the
incoming tweet, not a canned response.

Requires X API Basic tier for the mentions endpoint.
"""
from __future__ import annotations

import logging
from typing import Optional

from bot.brain.llm import complete as llm_complete
from bot.config import CLAUDE_MAX_TOKENS
from bot.state import State
from bot.x.client import get_mentions, post_tweet

log = logging.getLogger(__name__)

# Replies are limited to this many per engage run to avoid rate-limit issues.
MAX_REPLIES_PER_RUN = 5

_REPLY_SYSTEM = """\
You write short, genuine replies for @Qwinahh — a crypto commentary account on X.

Rules:
- Be direct and add something specific. No filler, no "great point", no agreement without substance.
- Max 240 characters.
- If the mention is hostile, spam, or not worth engaging: respond with SKIP.
- No price predictions. No hashtags. Sound like a person, not a bot.
- If you have a position in the mentioned project, end with (position disclosed).
"""


def _generate_reply(mention_text: str) -> Optional[str]:
    prompt = (
        f"Mention received:\n\n{mention_text}\n\n"
        "Write a reply that adds something specific, or respond with exactly SKIP if "
        "the mention is hostile, spam, or genuinely not worth engaging."
    )
    reply = llm_complete(system=_REPLY_SYSTEM, user=prompt, max_tokens=CLAUDE_MAX_TOKENS, temperature=0.7)
    if not reply:
        return None
    reply = reply.strip()
    if reply.upper().startswith("SKIP") or len(reply) < 10:
        log.debug("Skipping reply (model decided not to respond).")
        return None
    if len(reply) > 280:
        reply = reply[:276].rsplit(".", 1)[0] + "."
    return reply


def run(state: State) -> int:
    """
    Check for new mentions and reply to them.

    Returns the number of replies sent.
    """
    since_id = state._data.get("last_mention_id")
    mentions  = get_mentions(since_id=since_id)

    if not mentions:
        log.info("No new mentions.")
        return 0

    # Update the cursor so we don't re-process old mentions.
    newest_id = max(m["id"] for m in mentions)
    state._data["last_mention_id"] = newest_id

    already_replied = state.last_replied_to()
    replies_sent    = 0

    for mention in mentions:
        if replies_sent >= MAX_REPLIES_PER_RUN:
            break

        tweet_id = mention["id"]
        if tweet_id in already_replied:
            continue

        reply_text = _generate_reply(mention["text"])
        if not reply_text:
            continue

        sent_id = post_tweet(reply_text, reply_to_id=tweet_id)
        if sent_id:
            state.mark_replied(tweet_id)
            replies_sent += 1
            log.info("Replied to %s: %s", tweet_id, reply_text[:60])

    return replies_sent
